inherit_from: .rubocop_todo.yml

# Allow compact style in the tests.
Style/ClassAndModuleChildren:
  Exclude:
    - 'test/**/*'

# Don't require doc comments in general.
Style/Documentation:
  Enabled: false

# Allow complex methods
Metrics/AbcSize:
  Max: 60

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 20

# Allow long methods
Metrics/MethodLength:
  Max: 55
  Exclude:
    - 'test/**/*'

# Allow short param names.
Naming/MethodParameterName:
  Enabled: false

# Allow chaining blocks for solution efficiency.
Style/MultilineBlockChain:
  Enabled: false

# Turn this nonsense off.
Style/SymbolArray:
  EnforcedStyle: brackets

# Turn this nonsense off as well.
Style/WordArray:
  EnforcedStyle: brackets
